helm install db mongodb/
helm install nrf free5gc-nrf/
helm install amf free5gc-amf/
helm install ausf free5gc-ausf/
helm install n3iwf free5gc-n3iwf/
helm install nssf free5gc-nssf/
helm install pcf free5gc-pcf/
helm install smf free5gc-smf/
helm install udm free5gc-udm/
helm install udr free5gc-udr/
helm install upf free5gc-upf/
helm install webui free5gc-webui/