helm install db mongodb/
helm install nrf nrf/
helm install amf amf/
helm install ausf ausf/
helm install n3iwf n3iwf/
helm install nssf nssf/
helm install pcf pcf/
helm install udm udm/
helm install udr udr/
helm install smf smf/
helm install upf upf/
helm install webui webui/