apiVersion: v1
kind: Service
metadata:
  name: release-name-n3gpptester-service
  labels:
    helm.sh/chart: n3gpptester-0.1.0
    app.kubernetes.io/name: n3gpptester
    app.kubernetes.io/instance: release-name
    app: n3gpptester
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: n1
      port: 500
      targetPort: n1-ue
      protocol: UDP
  selector:
    app.kubernetes.io/name: n3gpptester
    app.kubernetes.io/instance: release-name
    app: n3gpptester
---
# Source: n3gpptester/templates/statefulset.yaml
#
# Software Name : 5G-all-in-one-helm
# SPDX-FileCopyrightText: Copyright (c) 2022
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at todo
# or see the "LICENSE" file for more details.
#
# Author: Gustavo Zanatta Bruno
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for ueransim-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-n3gpptester
  labels:
    helm.sh/chart: n3gpptester-0.1.0
    app.kubernetes.io/name: n3gpptester
    app.kubernetes.io/instance: release-name
    app: n3gpptester
    app.kubernetes.io/managed-by: Helm
spec:
  serviceName: release-name-n3gpptester-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: n3gpptester
      app.kubernetes.io/instance: release-name
      app: n3gpptester
  template:
    metadata:
      labels:
        app.kubernetes.io/name: n3gpptester
        app.kubernetes.io/instance: release-name
        app: n3gpptester
    spec:
      containers:
        - name: n3gpptester
          image: "fhgrings/ue-non3gpp:latest"
          imagePullPolicy: Always
          ports:
            - name: n1-ue
              containerPort: 500
              protocol: UDP
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          command: ["sleep"]
          args: ["1000000"]
          #command: ["./app"]
          #args: ["ue"]
          resources:
            limits:
              cpu: 400m
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 100Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
